name: build

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Latest ruby will only be tested on
        # - all rails versions in current major & latest minor rails version of the previous major
        #
        # Any unsupported ruby will only be tested on
        # - rails versions if their patch release is within 6 months of the Ruby EOL date
        # - No version of the current rails major
        #
        # 3.2 -> EOL Mar '26 -> Only test Rails versions initially released before Sep '26
        include:
          - { ruby: '4.0', gemfile: 'rails_7_2' }
          - { ruby: '4.0', gemfile: 'rails_8_0' }
          - { ruby: '4.0', gemfile: 'rails_8_1' }
          - { ruby: '3.2', gemfile: 'rails_7_0' }
          - { ruby: '3.2', gemfile: 'rails_7_1' }
          - { ruby: '3.2', gemfile: 'rails_7_2' }
          - { ruby: '3.2', gemfile: 'rails_8_0' }
        # Supported rubies will test all permissible supported rails versions
        ruby: ['3.3', '3.4']
        gemfile: ['rails_6_1', 'rails_7_0', 'rails_7_1', 'rails_7_2', 'rails_8_0', 'rails_8_1']
        exclude:
            # Rails 6.1 is now fully untested and will leave the support matrix soon. As our minimum Ruby is 3.2
            # Rails 8.x is fully supported across our entire matrix of rubies
          - { ruby: '3.2', gemfile: 'rails_6_1' }
          - { ruby: '3.3', gemfile: 'rails_6_1' }
          - { ruby: '3.4', gemfile: 'rails_6_1' }
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
      - run: bundle exec rubocop
      - run: bundle exec rake cucumber
